name: Terraform Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-validate:
    name: Terraform validation only
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.15.0

      - name: Terraform format check
        run: terraform fmt -recursive -check

      - name: Terraform init without backend
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform module init without backend
        run: terraform -chdir=modules/cloudflare-pages init -backend=false

      - name: Terraform module validate
        run: terraform -chdir=modules/cloudflare-pages validate
